{
 "title": "Diagnostics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "BBMeteo_addr",
    "query": "SHOW TAG VALUES WITH key = address"
   }
  ]
 },
 "panels": [
  { "title": "Living room", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 }, "options": { "content": " " } },
  { "title": "Outside - sunny side", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 6, "y": 0 }, "options": { "content": " " } },
  { "title": "Bedroom", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 0 }, "options": { "content": " " } },
  { "title": "Outside - shady side", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 }, "options": { "content": " " } },
  { "title": "Battery voltage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Battery voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "repeat": "BBMeteo_addr",
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bbmeteo",
     "select": [
      [
       { "params": [ "vcc" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$BBMeteo_addr$/" }
     ]
    }
   ]
  },
  {
   "title": "$BBMeteo_addr",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "repeat": "BBMeteo_addr",
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Vcc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bbmeteo",
     "select": [
      [
       { "params": [ "vcc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$BBMeteo_addr$/" }
     ]
    }
   ]
  },
  { "title": "Signal strength", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Signal strength",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "repeat": "BBMeteo_addr",
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bbmeteo",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$BBMeteo_addr$/" }
     ]
    }
   ]
  },
  {
   "title": "$BBMeteo_addr",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "repeat": "BBMeteo_addr",
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "RSSI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bbmeteo",
     "query": "SELECT distinct(\"rssi\") FROM \"bbmeteo\" WHERE (\"address\" = 'f261555d69d9') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$BBMeteo_addr$/" }
     ]
    }
   ]
  },
  { "title": "Delivery rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "cea3118ce7ab",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100 * $A / ( 3600 / $B)", "type": "math" }
   ]
  },
  {
   "title": "d8439cc8c1cd",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100 * $A / ( 3600 / $B)", "type": "math" }
   ]
  },
  {
   "title": "f261555d69d9",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100 * $A / ( 3600 / $B)", "type": "math" }
   ]
  },
  {
   "title": "f62ca793005e",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "100 * $A / ( 3600 / $B)", "type": "math" }
   ]
  },
  { "title": "Update rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Update rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 31 },
   "repeat": "BBMeteo_addr",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bbmeteo",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$BBMeteo_addr$/" }
     ]
    }
   ]
  },
  {
   "title": "$BBMeteo_addr",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "repeat": "BBMeteo_addr",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Update rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bbmeteo",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$BBMeteo_addr$/" }
     ]
    }
   ]
  },
  { "title": "Work time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Work time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 41 },
   "repeat": "BBMeteo_addr",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bbmeteo",
     "select": [
      [
       { "params": [ "work_time" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$BBMeteo_addr$/" }
     ]
    }
   ]
  },
  {
   "title": "$BBMeteo_addr",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
   "repeat": "BBMeteo_addr",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Work time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "bbmeteo",
     "select": [
      [
       { "params": [ "work_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "address", "operator": "=~", "value": "/^$BBMeteo_addr$/" }
     ]
    }
   ]
  },
  { "title": "One wire", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Update rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "onewire",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Work time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "onewire",
     "select": [
      [
       { "params": [ "work_time" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "28-00000d4a1c31",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Update rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "onewire",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "28-00000d4a1c31",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Work time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "onewire",
     "select": [
      [
       { "params": [ "work_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}